version: '3.8'
services:
   internetbanking:
      image: internet-banking:v1
      ports:
       - "81:80"
   mobilebanking:
      image: mobile-banking:v1
      ports:
       - "82:80"
   insurance:
      image: insurance:v1
      ports:
       - "83:80"
   loans:
      image: loans:v1
      ports:
       - "84:80"            